export const enum TransactionType {
  ALL = 'ALL',
  PAYA = 'PAYA',
  SATNA = 'SATNA',
  LOCAL = 'LOCAL',
  AUTO = 'AUTO',
  NONE = 'NONE',
}

export const enum OperationHistoryQueryKeys {
  OPERATION_HISTORY_DATA_TABLE = 'OPERATION-HISTORY-DATA-TABLE',
  OPERATION_HISTORY_DOWNLOAD_REQUEST_FILE = 'OPERATION-HISTORY-DOWNLOAD-REQUEST-FILE',
  OPERATION_HISTORY_DOWNLOAD_EXPORT_FILE = 'OPERATION-HISTORY-DOWNLOAD-EXPORT-FILE',
  OPERATION_HISTORY_DOWNLOAD_RECEIPT = 'OPERATION-HISTORY-DOWNLOAD-RECEIPT',
  OPERATION_HISTORY_PAYMENT_STATUS = 'OPERATION-HISTORY-PAYMENT-STATUS',
  OPERATION_HISTORY_DOWNLOAD_OFFLINE_FILE_REQUEST = 'OPERATION-HISTORY-DOWNLOAD-OFFLINE-FILE-REQUEST',
}

export const getOperationHistoryQueryKey = (filter: unknown, pagination: unknown) => [
  OperationHistoryQueryKeys.OPERATION_HISTORY_DATA_TABLE,
  filter,
  pagination,
];

export const enum Statuses {
  CONFIRMED = 'CONFIRMED',
  CREATED = 'CREATED',
  DENIED = 'DENIED',
  FINALIZED = 'FINALIZED',
  PARTIALLY_SUCCESS = 'PARTIALLY_SUCCESS',
  INITIATED = 'INITIATED',
  IN_PROGRESS = 'IN_PROGRESS',
  DETAILS_INSERTED = 'DETAILS_INSERTED',
  FILE_ERROR = 'FILE_ERROR',
  SUBMITTED = 'SUBMITTED',
  CANCELED = 'CANCELED',
  PROCESSING = 'PROCESSING',
  WAIT_TO_CONFIRM_OPERATION = 'WAIT_TO_CONFIRM_OPERATION',
  PENDING = 'PENDING',
  PAID = 'PAID',
  WRITTEN_TO_MQ = 'WRITTEN_TO_MQ',
  SUCCEED = 'SUCCEED',
  FAIL = 'FAIL',
  CONFLICT_RECORDS = 'CONFLICT_RECORDS',
  IN_OPERATION = 'IN_OPERATION',
  REVERTED = 'REVERTED',
  REVERT_FAILED = 'REVERT_FAILED',
  NONE = 'NONE',
  INACTIVE = 'INACTIVE',
}

export const enum DateRangeID {
  CURRENT = 'CURRENT',
  LAST24H = 'LAST24H',
  LAST3D = 'LAST3D',
  LAST7D = 'LAST7D',
  LAST1M = 'LAST1M',
  CUSTOM = 'CUSTOM',
}
export const enum RequestTypes {
  ONLINE = 'ONLINE',
  OFFLINE_ACH = 'OFFLINE_ACH',
  OFFLINE_SALARY = 'OFFLINE_SALARY',
}
