export const enum TransactionType {
  ALL = 'ALL',
  PAYA = 'PAYA',
  SATNA = 'SATNA',
  LOCAL = 'LOCAL',
  AUTO = 'AUTO',
  NONE = 'NONE',
}

export const enum RequestType {
  ALL = 'ALL',
  ONLINE = 'ONLINE',
  ACH = 'OFFLINE_ACH',
  OFFLINE = 'OFFLINE_SALARY',
}

export const enum DepositType {
  ALL = 'ALL',
  ACCOUNT_WITHDRAWAL = 'ACCOUNT_WITHDRAWAL',
  EXTERNAL_WITHDRAWAL = 'EXTERNAL_WITHDRAWAL',
}

export const enum ListRequestQueryKeys {
  LIST_REQUEST_HISTORY_DATA_TABLE = 'list-request-history-data-table',
  LIST_REQUEST_HISTORY_DOWNLOAD_REQUEST_FILE = 'list-request-history-download-request-file',
  LIST_REQUEST_HISTORY_DOWNLOAD_EXPORT_FILE = 'list-request-history-download-export-file',
  LIST_REQUEST_HISTORY_DOWNLOAD_RECEIPT = 'list-request-history-download-receipt',
  LIST_REQUEST_HISTORY_PAYMENT_STATUS = 'list-request-history-payment-status',
  QUERY_STATUS_DOWNLOAD_RECEIPT = 'QUERY_STATUS_DOWNLOAD_RECEIPT',
}

export const enum Statuses {
  INITIAL_REGISTER = 'INITIAL_REGISTER',
  WAIT_TO_SIGN = 'WAIT_TO_SIGN',
  CANCEL = 'CANCEL',
  CANCEL24 = 'CANCEL24',
  R_CANCEL24 = 'R_CANCEL24',
  CONFIRMED = 'CONFIRMED',
  PAYMENT_CREATED = 'PAYMENT_CREATED',
  CREATED = 'CREATED',
  DENIED = 'DENIED',
  PARTIALLY_SUCCESS = 'PARTIALLY_SUCCESS',
  INITIATED = 'INITIATED',
  IN_PROGRESS = 'IN_PROGRESS',
  DETAILS_INSERTED = 'DETAILS_INSERTED',
  FILE_ERROR = 'FILE_ERROR',
  SUBMITTED = 'SUBMITTED',
  CANCELED = 'CANCELED',
  PROCESSING = 'PROCESSING',
  PENDING = 'PENDING',
  PAID = 'PAID',
  WRITTEN_TO_MQ = 'WRITTEN_TO_MQ',
  SUCCEED = 'SUCCEED',
  SUCCESS = 'SUCCESS',
  FAIL = 'FAIL',
  FAILED = 'FAILED',
  CONFLICT_RECORDS = 'CONFLICT_RECORDS',
  IN_OPERATION = 'IN_OPERATION',
  REVERTED = 'REVERTED',
  REVERT_FAILED = 'REVERT_FAILED',
  CORE_FAILED = 'CORE_FAILED',
  CONFLICT = 'CONFLICT',
  WITHDRAW_FROM_ACC = 'WITHDRAW_FROM_ACC',
  CREDIT_TO_GL = 'CREDIT_TO_GL',
  WITHDRAW_FROM_ACC_FAILED = 'WITHDRAW_FROM_ACC_FAILED',
  NONE = 'NONE',
  VALIDATION_SUCCESS = 'VALIDATION_SUCCESS',
  VALIDATION_FAILURE = 'VALIDATION_FAILURE',
  ACTIVE = 'ACTIVE',
  INACTIVE = 'INACTIVE',
  WAIT_TO_CONFIRM_OPERATION = 'WAIT_TO_CONFIRM_OPERATION',
  FINALIZED = 'FINALIZED',
}

export const enum DateRangeID {
  CURRENT = 'CURRENT',
  LAST24H = 'LAST24H',
  LAST3D = 'LAST3D',
  LAST7D = 'LAST7D',
  LAST1M = 'LAST1M',
  CUSTOM = 'CUSTOM',
}

export const enum PageRoute {
  FILE_DETAILS = 'file-details',
  QUERY_STATUS = 'query-status',
}
