export enum StepRoute {
  NATIONAL_ID = 'NATIONAL_ID',
  ORGANIZATION_ID = 'ORGANIZATION_ID',
  CONFIRMATION = 'CONFIRMATION',
}

export enum AGENT_MANAGEMENT_QUERY_KEYS {
  SSN = 'SSN',
  LEGAL_SSN = 'LEGAL_SSN',
  AGENT_INFORMATION = 'AGENT_INFORMATION',
  CONFIRMATION = 'CONFIRMATION',
  REMOVE_AGENT = 'REMOVE_AGENT',
}
